# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

conform <- function(xs, h) {
    .Call(`_opa_conform`, xs, h)
}

sign_with_threshold <- function(xs, diff_threshold) {
    .Call(`_opa_sign_with_threshold`, xs, diff_threshold)
}

all_diffs <- function(xs) {
    .Call(`_opa_all_diffs`, xs)
}

ordering <- function(xs, pairing_type, diff_threshold) {
    .Call(`_opa_ordering`, xs, pairing_type, diff_threshold)
}

row_pcc <- function(xs, h, pairing_type, diff_threshold) {
    .Call(`_opa_row_pcc`, xs, h, pairing_type, diff_threshold)
}

pcc <- function(dat, h, pairing_type, diff_threshold) {
    .Call(`_opa_pcc`, dat, h, pairing_type, diff_threshold)
}

calc_cvalues <- function(pcc_out, nreps) {
    .Call(`_opa_calc_cvalues`, pcc_out, nreps)
}

