# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_conform <- function(xs, h) {
    .Call(`_opa_c_conform`, xs, h)
}

c_sign_with_threshold <- function(xs, diff_threshold) {
    .Call(`_opa_c_sign_with_threshold`, xs, diff_threshold)
}

c_all_diffs <- function(xs) {
    .Call(`_opa_c_all_diffs`, xs)
}

c_ordering <- function(xs, pairing_type, diff_threshold) {
    .Call(`_opa_c_ordering`, xs, pairing_type, diff_threshold)
}

c_row_pcc <- function(xs, h, pairing_type, diff_threshold) {
    .Call(`_opa_c_row_pcc`, xs, h, pairing_type, diff_threshold)
}

c_calc_cvalues <- function(pcc_out, nreps) {
    .Call(`_opa_c_calc_cvalues`, pcc_out, nreps)
}

