# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_sign_with_threshold <- function(xs, diff_threshold) {
    .Call(`_opa_c_sign_with_threshold`, xs, diff_threshold)
}

c_all_diffs <- function(xs) {
    .Call(`_opa_c_all_diffs`, xs)
}

c_random_shuffles <- function(n, v) {
    .Call(`_opa_c_random_shuffles`, n, v)
}

c_ordering <- function(xs, pairing_type, diff_threshold) {
    .Call(`_opa_c_ordering`, xs, pairing_type, diff_threshold)
}

c_compare_rand_pccs <- function(perms, m, indiv_idx, H_ord) {
    .Call(`_opa_c_compare_rand_pccs`, perms, m, indiv_idx, H_ord)
}

c_compare_perm_pccs <- function(perms, m, indiv_idx, H_ord) {
    .Call(`_opa_c_compare_perm_pccs`, perms, m, indiv_idx, H_ord)
}

